name: Deploy to Vercel on Release
env:
  #THIS IS PROJECT INFORMATION WHICH COMES FROM .VERCEL/PROJECT.JSON FILE.
  # THIS KEY VALUE STORE IN GITHUB ACTION. 
  # GITHUB.COM > SETTINGS > SECRETS AND VARIABLES > ACTIONS > REPOSITORY SECRETS.
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  release:
    types: [published]  # Déclenche le workflow uniquement lors de la publication d'une release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install  # ou yarn install si tu utilises Yarn

      - name: Build project
        run: npm run build  # assure-toi que ton projet est bien configuré pour se builder

      - name: Deploy Project to Vercel  
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
